### ISSUE TITLE
create docker

### ISSUE THREAD

**Issue by kozyraki** [mesosphere/mesos-dns-pkg#1]
Can we also add the functionality to build a simple docker for Mesos-dns?

The dockerfile should be as simple as:

FROM centos:centos7
COPY mesos-dns mesos-dns
EXPOSE 53

**Comment by lloesche** [comment]
Implemented. You can now build a mesosphere/mesos-dns Docker container which will first setup a CentOS 7 based system (docker-rootfs/) in which it builds mesos-dns and then creates a Minimal Docker rootfs with only mesos-dns and some libraries in it. This rootfs is used by a second Docker container "docker/" which gets tagged as mesosphere/mesos-dns
